### ISSUE TITLE
Error in Health Check script

### ISSUE THREAD

**Issue by Olivier6767** [sdr-enthusiasts/docker-adsbexchange#154]
I have the following error in the logs every 15 minutes:
`Traceback (most recent call last):
  File "/scripts/health_from_adsbexchange.py", line 9, in <module>
    stats_json = json.loads(stats_raw.decode('utf-8'))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

The issue seems to be with the health check script. When accessing the web page: http://www.adsbexchange.com/myip/ I get the following page
![myip screenshot](https://user-images.githubusercontent.com/28684355/229278538-5c9390a5-333a-4ad4-92f6-156bbb5d0fb0.jpg)

Here is the source code of this code that apparently fail JSON decode (IP address and Feeder ID redacted)
[page.txt](https://github.com/sdr-enthusiasts/docker-adsbexchange/files/11128986/page.txt)

**Comment by sriram-sridharan** [comment]
Yes, I see a similar issue in the `adsbexchange-feed` container logs:
```
Traceback (most recent call last):
  File "/scripts/health_from_adsbexchange.py", line 9, in <module>
    stats_json = json.loads(stats_raw.decode('utf-8'))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I'm assuming autoheal is triggered since the container is restarted after that. I see this happening a few times an hour since yesterday (atleast). I also see this connection timeout each time the health check error from above is thrown, unsure if related:
```
[mlat-client] Connection to feed2.adsbexchange.com:64590 lost: [Errno 110] Connection timed out
[mlat-client] Reconnecting in 0.5 seconds
[mlat-client] Connection to feed2.adsbexchange.com:64590 lost: [Errno 110] Connection timed out
[mlat-client] Reconnecting in 3.4 seconds
[mlat-client] Connected to multilateration server at feed1.adsbexchange.com:31090, handshaking
```

Happy to record/supply any other logs that are needed, thanks!

**Comment by klara31** [comment]
The health script is expecting a JSON from http://www.adsbexchange.com/myip/ but a HTML page is returned. Hence the health check fails.

**Comment by theyosh** [comment]
As a temporary work around I have disabled the heath check with:

```
  adsbx:
    image: ghcr.io/sdr-enthusiasts/docker-adsbexchange:latest
    tty: true
    container_name: adsbx
    restart: always
    healthcheck:
      disable: true
```
I added 
```
healthcheck:
      disable: true
```

And now the image is not restarted by autoheal and stays running. But this is a workaround. The health check should be refactored to work with the new HTML page like above

**Comment by dipalo** [comment]
I've been using the default bash `healthcheck.sh` rather than the python script. This too has been failing since the http://www.adsbexchange.com/myip/ page got updated. I've submitted the pull request above to fix the issue in this script.
