### ISSUE TITLE
Support 978Mhz UAT

### ISSUE THREAD

**Issue by echoz** [sdr-enthusiasts/docker-adsbexchange#69]
ADSBExchange now seems to support 978Mhz feeding as well. Possible to add this as an enhancement request?

https://www.adsbexchange.com/how-to-feed/

**Comment by mikenye** [comment]
Hi @echoz,

If you follow the steps here: <https://sdr-enthusiasts.gitbook.io/ads-b/foundations/deploy-dump978-usa-only>, the readsb container can ingest the data from dump978.

Then, all of your containers receiving BEAST data from readsb will be feeding UAT traffic.

Kind regards,
Mike Nye

**Comment by echoz** [comment]
Ahhhh! Already have that setup. Wasn't that obvious too me. Thank you!

**Comment by mikenye** [comment]
No problems! I should make the documentation on this repo clearer.

There are some feeders that explicitly want the raw UAT data (like rbfeeder/piaware/etc), and some that are happy for the data to come in via BEAST.
